version: '3.8'
services:
  web:
    image: productionwentdown/lwan
  db:
    image: 'mariadb:latest'
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
