version: '3.8'
services:
  web:
    image: lwan
  db:
    image: mariadb
    ports:
    - "8080:8080"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
