version: '3'
services:
  web:
    image: lwan
  db:
    image: mariadb
    ports:
    - "9090:9090"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
